source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'RealmJSONDemo' do
  pod 'AFNetworking'
  pod 'Realm+JSON', :path => '../'
end

target 'RealmJSONDemoTests' do
  pod 'Realm+JSON', :path => '../'
end
