source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'RealmJSONDemo' do
    pod 'AFNetworking'
    pod 'VLRealm+JSON', :path => '../'
    
    target 'RealmJSONDemoTests' do
        inherit! :search_paths
    end
end
